name = "teknodaim"
compatibility_date = "2024-05-03"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat" ]


[[d1_databases]]
binding = "DB"
database_name = "teknodaim"
database_id = "8efaeebd-8999-415d-a7fd-fb9abb402f68"
migrations_dir = "./src/lib/db/migrations"

[vars]
APP_ENV= "production"
GOOGLE_CLIENT_ID="174500547602-jf04fv159t267gkrtujm4ese9535stoe.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET="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"
GOOGLE_REDIRECT_URL="https://beta.teknodaim.com/auth/login/google/callback"
PUBLIC_DOMAIN="beta.teknodaim.com"
PUBLIC_WP_DOMAIN="media.teknodaim.com"
PUBLIC_WP_EN_SUBDOMAIN="en.teknodaim.com"
PUBLIC_SITE_URL="https://beta.teknodaim.com"
PUBLIC_API="https://beta.teknodaim.com/api"
PUBLIC_WP_API="https://media.teknodaim.com/graphql"
PUBLIC_SITE_TITLE="Teknodaim"
PUBLIC_SITE_DESCRIPTION="Teknodaim membahas perkembangan teknologi di dunia. Topik yang kami bahas antara lain berita game, review gadget, perkembangan sains, dll."
PUBLIC_FACEBOOK_USERNAME="teknodaim"
PUBLIC_TWITTER_USERNAME="teknodaimcom"
PUBLIC_INSTAGRAM_USERNAME="teknodaim_com"
PUBLIC_YOUTUBE_USERNAME="@Teknodaim"
PUBLIC_ADSENSE_CLIENT_ID="ca-pub-1431832394500017"
PUBLIC_GA_MEASUREMENT_ID="G-P4Y1YPM7SR"
PUBLIC_SUPPORT_EMAIL="support@teknodaim.com"
PUBLIC_WHATSAPP_NUMBER="6283822727338"
PUBLIC_ADDRESS="Jl. Bakti Pemuda, Drien Rampak, Johan Pahlawan, Kabupaten Aceh Barat, Aceh 23611"
PUBLIC_LOGO_URL="https://media.teknodaim.com/wp-content/uploads/2021/07/Teknodaim-Text-Logo-V3.png.webp"
PUBLIC_LOGO_OG_URL="https://media.teknodaim.com/wp-content/uploads/2019/06/Teknodaim-Wall-min.png"
PUBLIC_LOGO_OG_WIDTH="800px"
PUBLIC_LOGO_OG_HEIGHT="450px"
R2_BUCKET="teknodaim-2"
R2_REGION="auto"
R2_ACCOUNT_ID="6e7987b6d5b2c28790eb8d863cd23aba"
R2_ACCESS_KEY="dd8179b32540f1d773997ad35732c394"
R2_SECRET_KEY="4a6f8a6a52a017099cf29dcb0eabf1f864e80f5c4c224f8d4924f36ca7678ccc"
R2_DOMAIN="assets.teknodaim.com"
DIGIFLAZZ_USERNAME="weponig14JZW"
DIGIFLAZZ_API_KEY_DEV="dev-15887b10-bc31-11ed-be43-897c133ef6c3"
DIGIFLAZZ_API_KEY_PROD="a500fb70-feca-54c6-8c4b-0cc41e348e16"
DIGIFLAZZ_WEBHOOK_ID="Dz4eng"
DIGIFLAZZ_WEBHOOK_SECRET="superRahasia"
TRIPAY_API_KEY_DEV="DEV-rrqfcDk6AUYbUU3Njrgix7068TW1KZb7QC4gFRKK"
TRIPAY_PRIVATE_KEY_DEV="JqXhw-MqYBm-CM0xK-CFzP2-quh3o"
TRIPAY_API_KEY_PROD="LXHJzj88riX67rzSrOs3d1QPXREbqjd5rmL3ntMf"
TRIPAY_PRIVATE_KEY_PROD="9NP6T-OLKVU-3te9r-movl8-iir07"
TRIPAY_MERCHANT_CODE_DEV="T20278"
TRIPAY_MERCHANT_CODE_PROD="T20278"
