import {
  BiCheckSquare,
  BiChevronsLeft,
  BiChevronsRight,
  BiListOl,
  BiMovie,
  BiNews,
  BiStar,
  BiTrophy,
  BiTv,
} from "react-icons/bi"
import {
  FaAndroid,
  FaApple,
  FaAppleAlt,
  FaCoffee,
  FaEnvelope,
  FaFacebook,
  FaInstagram,
  FaLinkedinIn,
  FaLinux,
  FaPinterestP,
  FaPlaystation,
  FaPlusSquare,
  FaRedditAlien,
  FaStarHalfAlt,
  FaTelegramPlane,
  FaTiktok,
  FaWhatsapp,
  FaWindows,
  FaXbox,
  FaYoutube,
} from "react-icons/fa"
import { FaBolt, FaXTwitter } from "react-icons/fa6"
import { FcGoogle } from "react-icons/fc"
import { ImBook } from "react-icons/im"
import { IoGameController } from "react-icons/io5"
import {
  LuChevronDown,
  LuCircle,
  LuHeading1,
  LuHeading2,
  LuHeading3,
  LuHeading4,
  LuHeading5,
  LuLoader2,
  LuText,
  LuTrash,
} from "react-icons/lu"
import {
  MdAccessTime,
  MdAccountCircle,
  MdAddShoppingCart,
  MdAnalytics,
  MdCategory,
  MdChevronLeft,
  MdChevronRight,
  MdClose,
  MdCode,
  MdContentCopy,
  MdCurrencyExchange,
  MdDarkMode,
  MdDashboard,
  MdDeveloperBoard,
  MdDiamond,
  MdDiscount,
  MdDownload,
  MdFolder,
  MdFormatBold,
  MdFormatItalic,
  MdFormatListBulleted,
  MdFormatListNumbered,
  MdFormatQuote,
  MdFormatStrikethrough,
  MdFormatUnderlined,
  MdHelpOutline,
  MdHorizontalRule,
  MdImage,
  MdLightMode,
  MdLocationOn,
  MdLock,
  MdLogin,
  MdLogout,
  MdOutlineAdd,
  MdOutlineAdsClick,
  MdOutlineArrowBack,
  MdOutlineArrowDownward,
  MdOutlineArrowForward,
  MdOutlineArrowUpward,
  MdOutlineArticle,
  MdOutlineBalance,
  MdOutlineBrokenImage,
  MdOutlineCalendarMonth,
  MdOutlineCheck,
  MdOutlineComment,
  MdOutlineCreditCard,
  MdOutlineDelete,
  MdOutlineEdit,
  MdOutlineEditNote,
  MdOutlineFileUpload,
  MdOutlineHome,
  MdOutlineKeyboardArrowDown,
  MdOutlineLink,
  MdOutlineMenu,
  MdOutlineMoreHoriz,
  MdOutlineMoreVert,
  MdOutlinePermMedia,
  MdOutlineRefresh,
  MdOutlineSave,
  MdOutlineSearch,
  MdOutlineSettings,
  MdOutlineTableChart,
  MdOutlineTopic,
  MdOutlineViewSidebar,
  MdOutlineVisibility,
  MdOutlineVisibilityOff,
  MdPerson,
  MdSmartphone,
  MdStore,
  MdSupervisedUserCircle,
  MdTrendingUp,
  MdUpdate,
  MdVpnKey,
} from "react-icons/md"
import { SiNintendoswitch } from "react-icons/si"

import { IndonesiaFlag, USAFlag } from "./icon-flag"
import { LampIcon, VerifiedIcon } from "./icon-misc"

export const Icon = {
  AccessTime: MdAccessTime,
  Account: MdAccountCircle,
  Add: MdOutlineAdd,
  Ads: MdOutlineAdsClick,
  Analytics: MdAnalytics,
  Android: FaAndroid,
  Apple: FaApple,
  AppleAlt: FaAppleAlt,
  ArrowBack: MdOutlineArrowBack,
  ArrowDown: MdOutlineArrowDownward,
  ArrowUp: MdOutlineArrowUpward,
  ArrowForward: MdOutlineArrowForward,
  Article: MdOutlineArticle,
  Balance: MdOutlineBalance,
  Book: ImBook,
  Bolt: FaBolt,
  BrokenImage: MdOutlineBrokenImage,
  Calendar: MdOutlineCalendarMonth,
  Category: MdCategory,
  Check: MdOutlineCheck,
  CheckSquare: BiCheckSquare,
  ChevronLeft: MdChevronLeft,
  ChevronsLeft: BiChevronsLeft,
  ChevronRight: MdChevronRight,
  ChevronsRight: BiChevronsRight,
  ChevronDown: LuChevronDown,
  Circle: LuCircle,
  Close: MdClose,
  Code: MdCode,
  Coffe: FaCoffee,
  Comment: MdOutlineComment,
  Copy: MdContentCopy,
  CreditCard: MdOutlineCreditCard,
  Currency: MdCurrencyExchange,
  Dark: MdDarkMode,
  Dashboard: MdDashboard,
  Developer: MdDeveloperBoard,
  Diamond: MdDiamond,
  Discount: MdDiscount,
  Download: MdDownload,
  Delete: MdOutlineDelete,
  EditNote: MdOutlineEditNote,
  Edit: MdOutlineEdit,
  Email: FaEnvelope,
  USAFlag: USAFlag,
  Facebook: FaFacebook,
  Folder: MdFolder,
  FormatBold: MdFormatBold,
  FormatItalic: MdFormatItalic,
  FormatListBulleted: MdFormatListBulleted,
  FormatListNumbered: MdFormatListNumbered,
  FormatQuote: MdFormatQuote,
  FormatStrikethrough: MdFormatStrikethrough,
  FormatUnderlined: MdFormatUnderlined,
  Game: IoGameController,
  GoogleColored: FcGoogle,
  HalfStar: FaStarHalfAlt,
  H1: LuHeading1,
  H2: LuHeading2,
  H3: LuHeading3,
  H4: LuHeading4,
  H5: LuHeading5,
  Help: MdHelpOutline,
  Home: MdOutlineHome,
  HorizontalRule: MdHorizontalRule,
  Image: MdImage,
  IndonesiaFlag: IndonesiaFlag,
  Instagram: FaInstagram,
  KeyboardArrowDown: MdOutlineKeyboardArrowDown,
  Lamp: LampIcon,
  Light: MdLightMode,
  Link: MdOutlineLink,
  Linkedin: FaLinkedinIn,
  Linux: FaLinux,
  ListOl: BiListOl,
  Location: MdLocationOn,
  Lock: MdLock,
  Login: MdLogin,
  Logout: MdLogout,
  Media: MdOutlinePermMedia,
  Menu: MdOutlineMenu,
  MoreVert: MdOutlineMoreVert,
  MoreHorizontal: MdOutlineMoreHoriz,
  Moon: MdDarkMode,
  Movie: BiMovie,
  News: BiNews,
  NintendoSwitch: SiNintendoswitch,
  Person: MdPerson,
  Pinterest: FaPinterestP,
  PlayStation: FaPlaystation,
  PlusSquare: FaPlusSquare,
  Reddit: FaRedditAlien,
  Refresh: MdOutlineRefresh,
  Save: MdOutlineSave,
  Settings: MdOutlineSettings,
  Search: MdOutlineSearch,
  Shop: MdStore,
  ShoppingCart: MdAddShoppingCart,
  SignIn: MdLogin,
  SignOut: MdLogout,
  Spinner: LuLoader2,
  Smartphone: MdSmartphone,
  Star: BiStar,
  Sun: MdLightMode,
  Table: MdOutlineTableChart,
  Telegram: FaTelegramPlane,
  Text: LuText,
  Tiktok: FaTiktok,
  Topic: MdOutlineTopic,
  Trash: LuTrash,
  Trending: MdTrendingUp,
  Trophy: BiTrophy,
  TV: BiTv,
  Twitter: FaXTwitter,
  Update: MdUpdate,
  Upload: MdOutlineFileUpload,
  UploadFile: MdOutlineFileUpload,
  User: MdPerson,
  Users: MdSupervisedUserCircle,
  Verified: VerifiedIcon,
  ViewSidebar: MdOutlineViewSidebar,
  Visibility: MdOutlineVisibility,
  VisibilityOff: MdOutlineVisibilityOff,
  VpnKey: MdVpnKey,
  Xbox: FaXbox,
  WhatsApp: FaWhatsapp,
  Windows: FaWindows,
  Youtube: FaYoutube,
}
